services:
  frontend:
    #    depends_on:
    #      backend:
    #        condition: service_healthy
    #        restart: true
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: synergyWay/demo-frontend:latest
    ports:
      - 4200:4200
    networks:
      - myNetwork
  #    working_dir: /app
  #    volumes:
  #      - ./frontend:/app

  backend:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    image: synergyWay/demo-server:latest
    ports:
      - 3001:3001
    networks:
      - myNetwork
#    working_dir: /app
#    volumes:
#      - ./backend:/app
#    healthcheck:



networks:
  myNetwork:
    driver: bridge


